// Generated from https://hero-siege-helper.vercel.app/items/sets on 2026-05-16.
const SET_ITEM_NAMES = new Set<string>([
  "Abomination's Brain",
  "Abomination's Eye",
  "Abomination's Heart",
  "Angel",
  "Anubis Oculus",
  "Anubis Torso",
  "Anubis' Mighty Hands",
  "Arc's Sigil",
  "Arc's Walkers",
  "Aztec Crown",
  "Aztec Devil",
  "Aztec Necklace",
  "Aztec Ward",
  "Barrel of Explosives",
  "Battle Worn Boots",
  "Battle Worn Gauntlets",
  "Battle Worn Visor",
  "Blood-letter's Crown",
  "Blood-letter's Plate Body",
  "Blood-letter's Plated Boots",
  "Blood-letter's Plated Gauntlet",
  "Bob's Grenade",
  "Bone Conjurer's Grips",
  "Bone Conjurer's Marchers",
  "Bone Conjurer's Mask",
  "Bone Conjurer's Trophy",
  "Boots of Wild",
  "Bull's Eye",
  "Butcher's Apron",
  "Butcher's Belt",
  "Butcher's Hood",
  "Canopic Jar of Blood",
  "Champion's Fighting Gloves",
  "Champion's Flag Lance",
  "Champion's Medal of Valor",
  "Champion's Signet",
  "Chestplate of Fire",
  "Chronomancer's Curio of Time",
  "Chronomancer's Observance",
  "Chronomancer's Omnipotence",
  "Daisy",
  "Damien's Cage",
  "Damien's Head",
  "Damien's Soulstone",
  "Dante's Boots",
  "Dante's Demon Blade",
  "Dante's Jacket",
  "Dante's Mitts",
  "Death Lord's Bone Armor",
  "Death Lord's Crown",
  "Death Lord's Marchers",
  "Death Lord's Zombie Head",
  "Death's Grasp",
  "Death's Scythe",
  "Demon",
  "Demon's Ribcage",
  "Devil's Gem",
  "Devil's Grasp",
  "Dibbik Box",
  "Doctor's Grasp",
  "Doctor's Mask in a Jar",
  "Doctor's Potion",
  "Doctor's Visage",
  "Earth Shaper's Belt",
  "Earth Shaper's Body",
  "Earth Shaper's Boots",
  "Earth Shaper's Talons",
  "Einar's Horned Helmet",
  "Einar's Icy Stride",
  "Einar's Padded Gauntlets",
  "Einar's Plated Armor",
  "Engineer's Master Pendant",
  "Engineer's Mini Drone",
  "Engineer's Plated Vest",
  "Engineer's Toolbelt",
  "Flame Diviner's Cord",
  "Flame Diviner's Refuge",
  "Flame Diviner's Sanctum",
  "Flame Diviner's Ward",
  "Flaming Coin",
  "Flaming Marchers",
  "Gabriel's Brimmed Fedora",
  "Gabriel's Leather Trench Coat",
  "Genji's Battle Armor",
  "Genji's Battle Helmet",
  "Genji's Sword of Fate",
  "Gladiator's Battle Sandals",
  "Gladiator's Skullet",
  "Gladiator's Wall",
  "Gladiator's Wrecking Ball",
  "Gloves of Wilderness",
  "Gurag's Heart Charm",
  "Gurag's Pebble",
  "Gurag's Stone Crusher",
  "Hands of Flame",
  "Heart of Agony",
  "Hello its me, Steve!",
  "Insignia of the Hunter",
  "Juggernaut's Emblem",
  "Juggernaut's Glorious Plate",
  "Juggernaut's Siege Helm",
  "Juggernaut's Victory Marchers",
  "Justiciar's Thunder Armor",
  "Justiciar's Thunder Boots",
  "Justiciar's Thunder Sash",
  "Justiciar's Thunder Wall",
  "Lancer's Chestplate",
  "Lancer's Glory",
  "Lancers Gauntlets",
  "Lost Master's Gauntlets",
  "Lost Master's Marchers",
  "Lost Master's Platemail",
  "Lost Master's Vision",
  "Lumberjack's Chainsaw",
  "Lumberjack's Forestry Boots",
  "Lumberjack's Safety Gloves",
  "Lumberjack's Safety Helm",
  "Lunar Prophet's Band",
  "Lunar Prophet's Girdle",
  "Lunar Prophet's Tiara",
  "Lunar Prophet's Walkers",
  "Marksman's Hunting Bow",
  "Marksman's Hunting Gloves",
  "Marksman's Hunting Shroud",
  "Marksman's Quiver",
  "Masamune",
  "Mevius' Mighty Gauntlets",
  "Mevius' Mighty Helmet",
  "Mevius' Mighty Marchers",
  "Mevius' Mighty Plate",
  "Muramasa",
  "Mysterious Monkey Paw",
  "Nobunaga's Battle Cuirass",
  "Nobunaga's Battle Helmet",
  "Nobunaga's Battle Slicer",
  "Nobunaga's Warrior Spirit",
  "Nomad's Battlerobe",
  "Nomad's Sand Bandana",
  "Nomad's Sand Mitts",
  "Nomad's Sandslicer",
  "Odin's Battlearmor",
  "Odin's Eternal Visage",
  "Pirate Captain's Boots",
  "Pirate Captain's Flag",
  "Pirate Captain's Hat",
  "Pirate Captain's Shirt",
  "Plunderer's Deck Marchers",
  "Plunderer's Gunpowder Bag",
  "Plunderer's Jacket",
  "Plunderer's Spy Glass",
  "Prophet's Branch",
  "Prophet's Foliage",
  "Prophet's Pinecone",
  "Prophet's Shroud",
  "Reaper's Hood",
  "Redneck's Cap",
  "Redneck's Keychain",
  "Redneck's Working Boots",
  "Sacred Aegis",
  "Sacred Marchers",
  "Sacred Owl",
  "Sacred Pendant",
  "Sacred Robe",
  "Sand Manipulator's Authority",
  "Sand Manipulator's Kalasiris",
  "Sand Manipulator's Mask",
  "Satan's Cuirass",
  "Satan's Molten Steps",
  "Satan's Precious",
  "Sheep King's Crown",
  "Sheep King's Hide",
  "Sheep King's Wool",
  "Shield Bearer's Crown",
  "Shield Bearer's Greaves",
  "Shield Bearer's Plated Armor",
  "Shield Bearer's Wall",
  "Skinwalker's Claw",
  "Skinwalker's Mantle",
  "Skinwalker's Paw",
  "Skinwalker's Sigil",
  "Sniper's Scope",
  "Solar Prophet's Crown",
  "Solar Prophet's Robes",
  "Solar Prophet's Signet",
  "Solar Prophet's Tablet",
  "Spirit Pendant",
  "Steve's Bang",
  "Steve's Mighty Sword",
  "Steve's Necklace",
  "Steve's Punchbow",
  "Steve's Wand of Fortune",
  "Sundial of Ancient Worlds",
  "Tactical Flak Jacket",
  "Tal's Deathskull",
  "Tal's Pendant",
  "Telescope",
  "The Detonator",
  "Thor's Battle Cap",
  "Thor's Battle Gloves",
  "Thor's Battle Sword",
  "Thor's Chest Armor",
  "Thorn of Helheim",
  "Thunder Caller's Robe",
  "Thunder Caller's Sash",
  "Thunder Caller's Treads",
  "Thunder Caller's Veil",
  "Tiny Planet",
  "Traveler's Compass",
  "Traveler's Double Belt",
  "Traveler's Leather Jacket",
  "Traveler's Map Journal",
  "Uabel's Chest",
  "Uabel's Gloves",
  "Uabel's Helmet",
  "Uabel's Wand",
  "Vagabond's Marchers",
  "Vagabond's Strap",
  "Vagabond's Ward",
  "Vagabond's Wraps",
  "Valkyrie's Battle Raiment",
  "Valkyrie's Battle Shield",
  "Valkyrie's Thunder Javelin",
  "Valkyrie's Winged Helm",
  "Venom's Necklace",
  "Venom's Ribcage",
  "Venom's Skull",
  "Venom's Talons",
  "Viking's Sacred Axe",
  "Viking's Sacred Boots",
  "Viking's Sacred Helmet",
  "Wendigo Skull",
  "Ymir's Freezing Boots",
  "Ymir's Frozen Shroud",
  "Ymir's Frozen Tear",
  "Ymir's Frozen Vestment",
  "Zealot's Beads of Destruction",
  "Zealot's Book of Prophecy",
  "Zealot's Deathbringers",
  "Zealot's Guise of Doom",
  "Zeus' Battle Boots",
  "Zeus' Circlet",
]);

export function isSetItemName(name: string | undefined): boolean {
  return Boolean(name && SET_ITEM_NAMES.has(name));
}
